In [28]:
import torch
from torch.nn import Linear
import torch.nn as nn

In [6]:
torch.manual_seed(1)

In [24]:
model=Linear(in_features=1,out_features=1)

In [39]:
#Make sure this is two dimensional
x=torch.tensor([[0.0]])

In [42]:
yhat=model(x)
yhat

tensor([[0.5087]], grad_fn=<AddmmBackward>)

In [45]:
class LR(nn.Module):
    def __init__(self,in_size,out_size):
        nn.Module.__init__(self)
        self.linear=nn.Linear(in_size,out_size)
    def forward(self,x):
        out=self.linear(x)
        return out

In [46]:
model=LR(1,1)

In [47]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.1390]], requires_grad=True), Parameter containing:
tensor([-0.1224], requires_grad=True)]


In [48]:
x=torch.tensor([[1.0]])

In [49]:
yhat=model(x)

In [50]:
yhat

tensor([[0.0166]], grad_fn=<AddmmBackward>)